name: nf-core AWS full size tests
# This workflow is triggered on published releases.
# It can be additionally triggered manually with GitHub actions workflow dispatch button.
# It runs the -profile 'test_full' on AWS batch

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run-tower:
    name: Run AWS full tests
    if: github.repository == '{{ name }}'
    runs-on: ubuntu-latest
    steps:
      - name: Launch workflow via tower
        uses: nf-core/tower-action@master
        # TODO nf-core: You can customise AWS full pipeline tests as required
        # Add full size test data (but still relatively small datasets for few samples)
        # on the `test_full.config` test runs with only one set of parameters
        {% raw %}
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          bearer_token: ${{ secrets.TOWER_BEARER_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          pipeline: ${{ github.repository }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}{% endraw %}/work/{{ short_name }}/{% raw %}work-${{ github.sha }}{% endraw %}
          parameters: |
            {
              "outdir": "s3://{% raw %}${{ secrets.AWS_S3_BUCKET }}{% endraw %}/{{ short_name }}/{% raw %}results-${{ github.sha }}{% endraw %}"
            }
          profiles: '[ "test_full", "aws_tower" ]'

