name: nf-core AWS test
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.
# It runs the -profile 'test' on AWS batch

on:
  workflow_dispatch:
jobs:
  run-platform:
    name: Run AWS tests
    if: github.repository == '{{ name }}'
    runs-on: ubuntu-latest
    steps:
      # Launch workflow using Seqera Platform CLI tool action {%- raw %}
      - name: Launch workflow via Seqera Platform
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}{% endraw %}/work/{{ short_name }}/{% raw %}work-${{ github.sha }}{% endraw %}
          parameters: |
            {
              "outdir": "s3://{% raw %}${{ secrets.AWS_S3_BUCKET }}{% endraw %}/{{ short_name }}/{% raw %}results-test-${{ github.sha }}{% endraw %}"
            }
          profiles: test

      - uses: actions/upload-artifact@v4
        with:
          name: Seqera Platform debug log file
          path: |
            seqera_platform_action_*.log
            seqera_platform_action_*.json
