name: Test pipeline configurations

# Run the workflow when:
#  - dispatched manually
#  - when a PR is opened or reopened to main/master branch
#  - the head branch of the pull request is updated, i.e. if fixes for a release are pushed last minute to dev.
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

env:
  NXF_ANSI_LOG: false

jobs:
  test_configs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "24.10.1"

      - name: Check out pipeline code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Check the correct default config base of the nf-core configs
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: nextflow config -value params.custom_config_base .
          contains: https://raw.githubusercontent.com/nf-core/configs/master
          expected_result: PASSED

      - name: Check the correct inclusion of an existing institutional profile
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: nextflow config -profile google -o flat . # We will hopefully always have this profile in configs, even if some HPCs are retired.
          contains: "The nf-core framework" # Part of the citation, should always be printed if profile is included
          expected_result: PASSED

      - name: Check the failed inclusion of a non-existing institutional profile
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: nextflow config -profile GLaDOS -o flat .
          contains: "Unknown configuration profile: 'GLaDOS'"
          expected_result: PASSED

      - name: Check that offline prevents inclusion of nf-core configs
        uses: GuillaumeFalourd/assert-command-line-output@v2
        env:
          NXF_OFFLINE: true
        with:
          command_line: nextflow config -profile google -o flat .
          contains: "Unknown configuration profile: 'google'"
          expected_result: PASSED

      # Check that local nf-core configs are included also when offline is unfortunately not possible
      # nexflow run allows setting a param via the CLI, but nextflow config does not. Therefore --custom_config_base "./local_path" does not work.
