name: nf-core linting comment
# This workflow is triggered after the linting action is complete
# It posts an automated comment to the PR, even if the PR is coming from a fork {%- raw %}

on:
  workflow_run:
    workflows: ["nf-core linting"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download lint results
        uses: dawidd6/action-download-artifact@883bc3da0e2f55ddd0a8fc8e99378551c1991a55 # v13
        with:
          workflow: linting.yml
          workflow_conclusion: completed

      - name: Get PR number
        id: pr_number
        run: echo "pr_number=$(cat linting-logs/PR_number.txt)" >> $GITHUB_OUTPUT

      - name: Post PR comment
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.pr_number.outputs.pr_number }}
          path: linting-logs/lint_results.md {%- endraw %}
