contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #tools channel"
    url: https://nfcore.slack.com/channels/tools
    about: Discussion about the nf-core/tools package
