---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "{{ component_name_underscore }}"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "{{ bioconda if bioconda else 'YOUR-TOOL-HERE' }}"
