name: Fix linting from a comment
on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    # Only run if comment is on a PR with the main repo, and if it contains the magic keywords
    if: >
      contains(github.event.comment.html_url, '/pull/') &&
      contains(github.event.comment.body, '@nf-core-bot fix linting') &&
      github.repository == 'nf-core/tools'
    runs-on: self-hosted
    steps:
      # Use the @nf-core-bot token to check out so we can push later
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.nf_core_bot_auth_token }}

      # Action runs on the issue comment, so we don't get the PR by default
      # Use the gh cli to check out the PR
      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.nf_core_bot_auth_token }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Prettier
        run: npm install -g prettier @prettier/plugin-php

      - name: Run 'prettier --write'
        run: prettier --write ${GITHUB_WORKSPACE}

      - name: Run Black
        uses: psf/black@stable
        with:
          # Override to remove the default --check flag so that we make changes
          options: "--color"

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: python-isort
        uses: isort/isort-action@v1.0.0
        with:
          isortVersion: "latest"
          requirementsFiles: "requirements.txt requirements-dev.txt"

      - name: Commit & push changes
        run: |
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          git config push.default upstream
          git add .
          git status
          git commit -m "[automated] Fix code linting"
          git push
