name: Fix linting from a comment
on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    # Only run if comment is on a PR with the main repo, and if it contains the magic keywords
    if: >
      contains(github.event.comment.html_url, '/pull/') &&
      contains(github.event.comment.body, '@nf-core-bot fix linting') &&
      github.repository == 'nf-core/tools'
    runs-on: self-hosted
    steps:
      # Use the @nf-core-bot token to check out so we can push later
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.nf_core_bot_auth_token }}

      # indication that the linting is being fixed
      - name: React on comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes

      # Action runs on the issue comment, so we don't get the PR by default
      # Use the gh cli to check out the PR
      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.nf_core_bot_auth_token }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        id: pre-commit
        run: pre-commit run --all-files
        continue-on-error: true

      # indication that the linting has finished
      - name: react if linting finished succesfully
        if: ${{ steps.pre-commit.outcome }} == 'success'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: green_check_mark

      - name: Commit & push changes
        id: commit-and-push
        if: ${{ steps.pre-commit.outcome }} == 'failure'
        run: |
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          git config push.default upstream
          git add .
          git status
          git commit -m "[automated] Fix code linting"
          git push

      - name: react if linting errors were fixed
        if: ${{ steps.commit-and-push.outcome }} == 'success'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: pencil2

      - name: react if linting errors were not fixed
        if: ${{ steps.commit-and-push.outcome }} == 'failure'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: x
          body: |
            @${{ github.actor }} I tried to fix the linting errors, but it didn't work. Please fix them manually.
