name: self-hosted test workflow
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NXF_ANSI_LOG: false

jobs:
  RunTestWorkflow:
    runs-on: self-hosted
    env:
      NXF_ANSI_LOG: false
    steps:
      - uses: actions/checkout@v3
        name: Check out source-code repository

      - name: check installed python version
        run: |
          echo "Python Version:"
          python -c "import sys; print(sys.version)"
          echo "AGENT_TOOLSDIRECTORY: $AGENT_TOOLSDIRECTORY"

      # - name: Set up Python 3.11
      #   uses: actions/setup-python@v4
      #   env:
      #     AGENT_TOOLSDIRECTORY: ${{ runner.tool_cache }}
      #   with:
      #     python-version: 3.11

      # - name: Install python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install .

      # - name: Install Nextflow
      #   uses: nf-core/setup-nextflow@v1
      #   with:
      #     version: ${{ matrix.NXF_VER }}

      # - name: Run nf-core/tools
      #   run: |
      #     nf-core --log-file log.txt create -n testpipeline -d "This pipeline is for testing" -a "Testing McTestface" --plain
      #     nextflow run nf-core-testpipeline -profile test,docker --outdir ./results

      # - name: Upload log file artifact
      #   if: ${{ always() }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: nf-core-log-file
      #     path: log.txt
